INSERT INTO Agents (AgentName) VALUES ("Arlene Martin");
INSERT INTO Agents (AgentName) VALUES ("Margaret Landry");
INSERT INTO Agents (AgentName) VALUES ("Austin Martin");

INSERT INTO Countries (CountryName) VALUES ('Afghanistan');
INSERT INTO Countries (CountryName) VALUES ('Albania');
INSERT INTO Countries (CountryName) VALUES ('Algeria');
INSERT INTO Countries (CountryName) VALUES ('American Samoa');
INSERT INTO Countries (CountryName) VALUES ('Andorra');
INSERT INTO Countries (CountryName) VALUES ('Angola');
INSERT INTO Countries (CountryName) VALUES ('Anguilla');
INSERT INTO Countries (CountryName) VALUES ('Antarctica');
INSERT INTO Countries (CountryName) VALUES ('Antigua and Barbuda');
INSERT INTO Countries (CountryName) VALUES ('Argentina');
INSERT INTO Countries (CountryName) VALUES ('Armenia');
INSERT INTO Countries (CountryName) VALUES ('Aruba');
INSERT INTO Countries (CountryName) VALUES ('Australia');
INSERT INTO Countries (CountryName) VALUES ('Austria');
INSERT INTO Countries (CountryName) VALUES ('Azerbaijan');
INSERT INTO Countries (CountryName) VALUES ('Bahamas');
INSERT INTO Countries (CountryName) VALUES ('Bahrain');
INSERT INTO Countries (CountryName) VALUES ('Bangladesh');
INSERT INTO Countries (CountryName) VALUES ('Barbados');
INSERT INTO Countries (CountryName) VALUES ('Belarus');
INSERT INTO Countries (CountryName) VALUES ('Belgium');
INSERT INTO Countries (CountryName) VALUES ('Belize');
INSERT INTO Countries (CountryName) VALUES ('Benin');
INSERT INTO Countries (CountryName) VALUES ('Bermuda');
INSERT INTO Countries (CountryName) VALUES ('Bhutan');
INSERT INTO Countries (CountryName) VALUES ('Bosnia and Herzegovina');
INSERT INTO Countries (CountryName) VALUES ('Botswana');
INSERT INTO Countries (CountryName) VALUES ('Bouvet Island');
INSERT INTO Countries (CountryName) VALUES ('Brazil');
INSERT INTO Countries (CountryName) VALUES ('British Indian Ocean Territory');
INSERT INTO Countries (CountryName) VALUES ('Brunei Darussalam');
INSERT INTO Countries (CountryName) VALUES ('Bulgaria');
INSERT INTO Countries (CountryName) VALUES ('Burkina Faso');
INSERT INTO Countries (CountryName) VALUES ('Burundi');
INSERT INTO Countries (CountryName) VALUES ('Cambodia');
INSERT INTO Countries (CountryName) VALUES ('Cameroon');
INSERT INTO Countries (CountryName) VALUES ('Canada');
INSERT INTO Countries (CountryName) VALUES ('Cape Verde');
INSERT INTO Countries (CountryName) VALUES ('Cayman Islands');
INSERT INTO Countries (CountryName) VALUES ('Central African Republic');
INSERT INTO Countries (CountryName) VALUES ('Chad');
INSERT INTO Countries (CountryName) VALUES ('Chile');
INSERT INTO Countries (CountryName) VALUES ('China');
INSERT INTO Countries (CountryName) VALUES ('Christmas Island');
INSERT INTO Countries (CountryName) VALUES ('Cocos (Keeling) Islands');
INSERT INTO Countries (CountryName) VALUES ('Colombia');
INSERT INTO Countries (CountryName) VALUES ('Comoros');
INSERT INTO Countries (CountryName) VALUES ('Congo');
INSERT INTO Countries (CountryName) VALUES ('Cook Islands');
INSERT INTO Countries (CountryName) VALUES ('Costa Rica');
INSERT INTO Countries (CountryName) VALUES ('Croatia');
INSERT INTO Countries (CountryName) VALUES ('Cuba');
INSERT INTO Countries (CountryName) VALUES ('Cyprus');
INSERT INTO Countries (CountryName) VALUES ('Czech Republic');
INSERT INTO Countries (CountryName) VALUES ('Denmark');
INSERT INTO Countries (CountryName) VALUES ('Djibouti');
INSERT INTO Countries (CountryName) VALUES ('Dominica');
INSERT INTO Countries (CountryName) VALUES ('Dominican Republic');
INSERT INTO Countries (CountryName) VALUES ('Ecuador');
INSERT INTO Countries (CountryName) VALUES ('Egypt');
INSERT INTO Countries (CountryName) VALUES ('El Salvador');
INSERT INTO Countries (CountryName) VALUES ('Equatorial Guinea');
INSERT INTO Countries (CountryName) VALUES ('Eritrea');
INSERT INTO Countries (CountryName) VALUES ('Estonia');
INSERT INTO Countries (CountryName) VALUES ('Ethiopia');
INSERT INTO Countries (CountryName) VALUES ('Falkland Islands (Malvinas)');
INSERT INTO Countries (CountryName) VALUES ('Faroe Islands');
INSERT INTO Countries (CountryName) VALUES ('Fiji');
INSERT INTO Countries (CountryName) VALUES ('Finland');
INSERT INTO Countries (CountryName) VALUES ('France');
INSERT INTO Countries (CountryName) VALUES ('French Guiana');
INSERT INTO Countries (CountryName) VALUES ('French Polynesia');
INSERT INTO Countries (CountryName) VALUES ('French Southern Territories');
INSERT INTO Countries (CountryName) VALUES ('Gabon');
INSERT INTO Countries (CountryName) VALUES ('Gambia');
INSERT INTO Countries (CountryName) VALUES ('Georgia');
INSERT INTO Countries (CountryName) VALUES ('Germany');
INSERT INTO Countries (CountryName) VALUES ('Ghana');
INSERT INTO Countries (CountryName) VALUES ('Gibraltar');
INSERT INTO Countries (CountryName) VALUES ('Greece');
INSERT INTO Countries (CountryName) VALUES ('Greenland');
INSERT INTO Countries (CountryName) VALUES ('Grenada');
INSERT INTO Countries (CountryName) VALUES ('Guadeloupe');
INSERT INTO Countries (CountryName) VALUES ('Guam');
INSERT INTO Countries (CountryName) VALUES ('Guatemala');
INSERT INTO Countries (CountryName) VALUES ('Guernsey');
INSERT INTO Countries (CountryName) VALUES ('Guinea');
INSERT INTO Countries (CountryName) VALUES ('Guinea-Bissau');
INSERT INTO Countries (CountryName) VALUES ('Guyana');
INSERT INTO Countries (CountryName) VALUES ('Haiti');
INSERT INTO Countries (CountryName) VALUES ('Heard Island and McDonald Islands');
INSERT INTO Countries (CountryName) VALUES ('Holy See (Vatican City State)');
INSERT INTO Countries (CountryName) VALUES ('Honduras');
INSERT INTO Countries (CountryName) VALUES ('Hong Kong');
INSERT INTO Countries (CountryName) VALUES ('Hungary');
INSERT INTO Countries (CountryName) VALUES ('Iceland');
INSERT INTO Countries (CountryName) VALUES ('India');
INSERT INTO Countries (CountryName) VALUES ('Indonesia');
INSERT INTO Countries (CountryName) VALUES ('Iraq');
INSERT INTO Countries (CountryName) VALUES ('Ireland');
INSERT INTO Countries (CountryName) VALUES ('Isle of Man');
INSERT INTO Countries (CountryName) VALUES ('Israel');
INSERT INTO Countries (CountryName) VALUES ('Italy');
INSERT INTO Countries (CountryName) VALUES ('Jamaica');
INSERT INTO Countries (CountryName) VALUES ('Japan');
INSERT INTO Countries (CountryName) VALUES ('Jersey');
INSERT INTO Countries (CountryName) VALUES ('Jordan');
INSERT INTO Countries (CountryName) VALUES ('Kazakhstan');
INSERT INTO Countries (CountryName) VALUES ('Kenya');
INSERT INTO Countries (CountryName) VALUES ('Kiribati');
INSERT INTO Countries (CountryName) VALUES ('Kuwait');
INSERT INTO Countries (CountryName) VALUES ('Kyrgyzstan');
INSERT INTO Countries (CountryName) VALUES ('Lao Peoples Democratic Republic');
INSERT INTO Countries (CountryName) VALUES ('Latvia');
INSERT INTO Countries (CountryName) VALUES ('Lebanon');
INSERT INTO Countries (CountryName) VALUES ('Lesotho');
INSERT INTO Countries (CountryName) VALUES ('Liberia');
INSERT INTO Countries (CountryName) VALUES ('Libya');
INSERT INTO Countries (CountryName) VALUES ('Liechtenstein');
INSERT INTO Countries (CountryName) VALUES ('Lithuania');
INSERT INTO Countries (CountryName) VALUES ('Luxembourg');
INSERT INTO Countries (CountryName) VALUES ('Macao');
INSERT INTO Countries (CountryName) VALUES ('Madagascar');
INSERT INTO Countries (CountryName) VALUES ('Malawi');
INSERT INTO Countries (CountryName) VALUES ('Malaysia');
INSERT INTO Countries (CountryName) VALUES ('Maldives');
INSERT INTO Countries (CountryName) VALUES ('Mali');
INSERT INTO Countries (CountryName) VALUES ('Malta');
INSERT INTO Countries (CountryName) VALUES ('Marshall Islands');
INSERT INTO Countries (CountryName) VALUES ('Martinique');
INSERT INTO Countries (CountryName) VALUES ('Mauritania');
INSERT INTO Countries (CountryName) VALUES ('Mauritius');
INSERT INTO Countries (CountryName) VALUES ('Mayotte');
INSERT INTO Countries (CountryName) VALUES ('Mexico');
INSERT INTO Countries (CountryName) VALUES ('Monaco');
INSERT INTO Countries (CountryName) VALUES ('Mongolia');
INSERT INTO Countries (CountryName) VALUES ('Montenegro');
INSERT INTO Countries (CountryName) VALUES ('Montserrat');
INSERT INTO Countries (CountryName) VALUES ('Morocco');
INSERT INTO Countries (CountryName) VALUES ('Mozambique');
INSERT INTO Countries (CountryName) VALUES ('Myanmar');
INSERT INTO Countries (CountryName) VALUES ('Namibia');
INSERT INTO Countries (CountryName) VALUES ('Nauru');
INSERT INTO Countries (CountryName) VALUES ('Nepal');
INSERT INTO Countries (CountryName) VALUES ('Netherlands');
INSERT INTO Countries (CountryName) VALUES ('New Caledonia');
INSERT INTO Countries (CountryName) VALUES ('New Zealand');
INSERT INTO Countries (CountryName) VALUES ('Nicaragua');
INSERT INTO Countries (CountryName) VALUES ('Niger');
INSERT INTO Countries (CountryName) VALUES ('Nigeria');
INSERT INTO Countries (CountryName) VALUES ('Niue');
INSERT INTO Countries (CountryName) VALUES ('Norfolk Island');
INSERT INTO Countries (CountryName) VALUES ('Northern Mariana Islands');
INSERT INTO Countries (CountryName) VALUES ('Norway');
INSERT INTO Countries (CountryName) VALUES ('Oman');
INSERT INTO Countries (CountryName) VALUES ('Pakistan');
INSERT INTO Countries (CountryName) VALUES ('Palau');
INSERT INTO Countries (CountryName) VALUES ('Panama');
INSERT INTO Countries (CountryName) VALUES ('Papua New Guinea');
INSERT INTO Countries (CountryName) VALUES ('Paraguay');
INSERT INTO Countries (CountryName) VALUES ('Peru');
INSERT INTO Countries (CountryName) VALUES ('Philippines');
INSERT INTO Countries (CountryName) VALUES ('Pitcairn');
INSERT INTO Countries (CountryName) VALUES ('Poland');
INSERT INTO Countries (CountryName) VALUES ('Portugal');
INSERT INTO Countries (CountryName) VALUES ('Puerto Rico');
INSERT INTO Countries (CountryName) VALUES ('Qatar');
INSERT INTO Countries (CountryName) VALUES ('Romania');
INSERT INTO Countries (CountryName) VALUES ('Russian Federation');
INSERT INTO Countries (CountryName) VALUES ('Rwanda');
INSERT INTO Countries (CountryName) VALUES ('Saint Kitts and Nevis');
INSERT INTO Countries (CountryName) VALUES ('Saint Lucia');
INSERT INTO Countries (CountryName) VALUES ('Saint Martin (French part)');
INSERT INTO Countries (CountryName) VALUES ('Saint Pierre and Miquelon');
INSERT INTO Countries (CountryName) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO Countries (CountryName) VALUES ('Samoa');
INSERT INTO Countries (CountryName) VALUES ('San Marino');
INSERT INTO Countries (CountryName) VALUES ('Sao Tome and Principe');
INSERT INTO Countries (CountryName) VALUES ('Saudi Arabia');
INSERT INTO Countries (CountryName) VALUES ('Senegal');
INSERT INTO Countries (CountryName) VALUES ('Serbia');
INSERT INTO Countries (CountryName) VALUES ('Seychelles');
INSERT INTO Countries (CountryName) VALUES ('Sierra Leone');
INSERT INTO Countries (CountryName) VALUES ('Singapore');
INSERT INTO Countries (CountryName) VALUES ('Sint Maarten (Dutch part)');
INSERT INTO Countries (CountryName) VALUES ('Slovakia');
INSERT INTO Countries (CountryName) VALUES ('Slovenia');
INSERT INTO Countries (CountryName) VALUES ('Solomon Islands');
INSERT INTO Countries (CountryName) VALUES ('Somalia');
INSERT INTO Countries (CountryName) VALUES ('South Africa');
INSERT INTO Countries (CountryName) VALUES ('South Sudan');
INSERT INTO Countries (CountryName) VALUES ('Spain');
INSERT INTO Countries (CountryName) VALUES ('Sri Lanka');
INSERT INTO Countries (CountryName) VALUES ('Sudan');
INSERT INTO Countries (CountryName) VALUES ('Suriname');
INSERT INTO Countries (CountryName) VALUES ('Svalbard and Jan Mayen');
INSERT INTO Countries (CountryName) VALUES ('Swaziland');
INSERT INTO Countries (CountryName) VALUES ('Sweden');
INSERT INTO Countries (CountryName) VALUES ('Switzerland');
INSERT INTO Countries (CountryName) VALUES ('Syrian Arab Republic');
INSERT INTO Countries (CountryName) VALUES ('Tajikistan');
INSERT INTO Countries (CountryName) VALUES ('Thailand');
INSERT INTO Countries (CountryName) VALUES ('Timor-Leste');
INSERT INTO Countries (CountryName) VALUES ('Togo');
INSERT INTO Countries (CountryName) VALUES ('Tokelau');
INSERT INTO Countries (CountryName) VALUES ('Tonga');
INSERT INTO Countries (CountryName) VALUES ('Trinidad and Tobago');
INSERT INTO Countries (CountryName) VALUES ('Tunisia');
INSERT INTO Countries (CountryName) VALUES ('Turkey');
INSERT INTO Countries (CountryName) VALUES ('Turkmenistan');
INSERT INTO Countries (CountryName) VALUES ('Turks and Caicos Islands');
INSERT INTO Countries (CountryName) VALUES ('Tuvalu');
INSERT INTO Countries (CountryName) VALUES ('Uganda');
INSERT INTO Countries (CountryName) VALUES ('Ukraine');
INSERT INTO Countries (CountryName) VALUES ('United Arab Emirates');
INSERT INTO Countries (CountryName) VALUES ('United Kingdom');
INSERT INTO Countries (CountryName) VALUES ('United States');
INSERT INTO Countries (CountryName) VALUES ('United States Minor Outlying Islands');
INSERT INTO Countries (CountryName) VALUES ('Uruguay');
INSERT INTO Countries (CountryName) VALUES ('Uzbekistan');
INSERT INTO Countries (CountryName) VALUES ('Vanuatu');
INSERT INTO Countries (CountryName) VALUES ('Viet Nam');
INSERT INTO Countries (CountryName) VALUES ('Wallis and Futuna');
INSERT INTO Countries (CountryName) VALUES ('Western Sahara');
INSERT INTO Countries (CountryName) VALUES ('Yemen');
INSERT INTO Countries (CountryName) VALUES ('Zambia');
INSERT INTO Countries (CountryName) VALUES ('Zimbabwe');